name: money_flow
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.0
  sqflite: ^2.4.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  fl_chart: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/usuario.png
    - assets/images/llave.png
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/inicio.png
    - assets/images/estadisticas.png
    - assets/images/ingresos.png
    - assets/images/presupuesto.png
    - assets/images/plus_sign.png
    - assets/images/linea.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
